#!/bin/sh
bspc rule -r "*"
#Laptop bg
BACKGROUND="/home/z/Images/wallpapers/wallhaven-493ve8.jpg"
#Battlestation bg
BACKGROUND_MON_1="/home/z/Images/wallpapers/Best/wallhaven-j5qgk5.jpg"
BACKGROUND_MON_2="/home/z/Images/wallpapers/Best/wallhaven-j5vvry.png"
BACKGROUND_MON_3="/home/z/Images/wallpapers/Best/wallhaven-j5p7pp.png"



		###---Autostart---###
sxhkd -a space &
xrdb ~/.Xresources 
~/.scripts/setUsCtrlSwap.sh
killall nm-applet
nm-applet &
killall pa-applet
pa-applet &
killall udiskie
udiskie --no-automount --tray &
#reset before applying 
redshift -x
redshift -l 38.7:-9.1  -t 5700:3600 -g 0.8 -m randr -v &
# pidof bspswallow || bspswallow &


#wal persist on reboot
# wal -i "$(< "${HOME}/.cache/wal/wal")"
#Change colorscheme without changing wallpaper
# wal -n -i IMAGE

#TODO 

#sleep and exec picom
~/.scripts/sleepAndExec.sh "picom --config /home/z/.config/picom/picom.config" &

#Specific autostarts
 if [[ $(hostname) == 'dracul' ]]; then
	 feh --bg-scale $BACKGROUND &
	 xset -b  #remove beep
	 ~/.config/polybar/launch_laptop.sh &
	 blueman-applet &


	 #Gif desktop background. Expensive on cpu
	# xwinwrap -g 200x200+840+490 -fdt -o 0.7 -sh circle -d -- gifview -w WID ~/.config/bspwm/quarksmall.gif -a

	 # wal -R -n -q 

 elif [[ $(hostname) == 'Battlestation' ]]; then
	 # ~/.scripts/screenlayout.sh &
	 ~/.screenlayout/1mon.sh &
	 ~/.config/polybar/launch_desktop.sh &
	 #change trackball buttons
	xinput set-button-map `xinput list | grep Trackball | cut -d "=" -f 2 | cut -c-2` 3 2 1
	# feh --bg-scale $BACKGROUND_MON_1 $BACKGROUND_MON_2 $BACKGROUND_MON_3 &
	feh --bg-scale $BACKGROUND_MON_1 &

 elif [[ $(hostname) == 'c3po' ]]; then
	feh --bg-scale /home/z/.scripts/setup/resources/Arch2.jpg
	 ~/.config/polybar/launch_vm.sh &

	 #Load vbox modules
	  modprobe -a vboxguest vboxsf vboxvideo
	  VBoxClient --clipboard
 fi


###---MONITORS---###
 if [[ $(hostname) == 'dracul' ]]; then
     bspc monitor eDP1 -d 1 2 3 4 7 8 5 6 

	 bsp-layout set tall 1
	 bsp-layout set tall 2
	 bsp-layout set tall 3
	 bsp-layout set tall 4
	 bsp-layout set tall 5
	 bsp-layout set tall 6
 elif [[ $(hostname) == 'Battlestation' ]]; then

	 # bspc monitor HDMI-0 -d 2 5 7 8
     # bspc monitor DP-0 -d 1 4
     # bspc monitor DP-2 -d 3 6 9 

     bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9

	 bsp-layout set even 1
	 bsp-layout set tall 2
	 bsp-layout set tiled 3
	 bsp-layout set even 4
	 bsp-layout set tall 5
	 bsp-layout set tiled 6
 elif [[ $(hostname) == 'c3po' ]]; then
     bspc monitor -d 1 2 3 4 5 6 7 
	 bsp-layout set tall 1
	 bsp-layout set tall 2
	 bsp-layout set tall 3
	 bsp-layout set tall 4
	 bsp-layout set tall 5
	 bsp-layout set tall 6
 fi




###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color6"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# bspc config normal_border_color	"4c566a"
# bspc config active_border_color	"#1e1e1e"
# bspc config focused_border_color "#406ea5"
# bspc config presel_feedback_color	"#5e81ac"
# bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10
bspc config borderless_monocle true
bspc config gapless_monocle false

###---Rules---###
bspc rule -a "Zathura" state=tiled
bspc rule -a Opera desktop=5
bspc rule -a Spotify desktop=8
bspc rule -a URxvt:Music desktop=8
bspc rule -a St:MusicVis desktop=8 
bspc rule -a URxvt:TempD1 desktop=1 
bspc rule -a Gnome-disks state=floating


bspc rule -a URxvt:youtubi state=floating sticky=on rectangle=500x100+250+120
# bspc rule -a firefox sticky=on state=floating rectangle=930x1020+10+40
bspc rule -a KeePassXC sticky=on state=floating 
#Temp terminals
bspc rule -a St:TempQ1 state=floating rectangle=930x510+10+40
bspc rule -a St:TempQ2 state=floating rectangle=930x510+10+560
bspc rule -a St:TempQ3 state=floating rectangle=930x510+980+40
bspc rule -a St:TempQ4 state=floating rectangle=930x510+980+560
bspc rule -a St:TempH1 state=floating rectangle=930x1020+10+40
bspc rule -a URxvt:TempH1 state=floating rectangle=930x1020+10+40
bspc rule -a St:TempH2 state=floating rectangle=930x1020+980+40
bspc rule -a St:TempScript1 state=floating rectangle=930x510+10+40
bspc rule -a St:TempScript2 state=floating rectangle=930x510+980+40
# bspc rule -a St:TempH1 state=floating rectangle=930x1020+10+40

bspc rule -a URxvt:Music state=floating rectangle=1030x520+450+80
bspc rule -a St:MusicVis state=floating rectangle=1500x350+200+720 border=off

~/.scripts/bspwm/bsp_floating_workspace &
# ~/.scripts/bspwm/bsp_pseudotiling_workspace &
~/.scripts/sleepAndExec.sh picom &
unclutter & #Hide mouse when not moved
