#!/bin/sh
bspc rule -r "*"



		###---Autostart---###
sxhkd -a space &
xrdb ~/.Xresources 
~/.scripts/setUsCtrlSwap.sh
killall nm-applet
nm-applet &
killall pa-applet
pa-applet &
killall udiskie
udiskie --no-automount --tray &
killall redshift
redshift -l 38.7:-9.1  -t 5700:3600 -g 0.8 -m randr -v &

#TODO 
#sleep and exec picom
~/.scripts/sleepAndExec.sh picom &

#Specific autostarts
 if [[ $(hostname) == 'dracul' ]]; then
	feh --bg-scale /home/z/Images/wallpapers/Arch1.png 
	 ~/.config/polybar/launch_laptop.sh &
	 blueman-applet &

	 # xwinwrap -g 200x200+583+283 -fdt -o 0.7 -sh circle -d -- gifview -w WID ~/.config/bspwm/quarksmall.gif -a

 elif [[ $(hostname) == 'Battlestation' ]]; then
	 ~/.scripts/screenlayout.sh &
	 ~/.config/polybar/launch_desktop.sh &
	 #change trackball buttons
	xinput set-button-map `xinput list | grep Trackball | cut -d "=" -f 2 | cut -c-2` 3 2 1
	 nitrogen --restore &

 elif [[ $(hostname) == 'c3po' ]]; then
	feh --bg-scale /home/z/.scripts/setup/resources/Arch2.jpg
	 ~/.config/polybar/launch_vm.sh &

	 #Load vbox modules
	  modprobe -a vboxguest vboxsf vboxvideo
	  VBoxClient --clipboard
 fi


###---MONITORS---###
 if [[ $(hostname) == 'dracul' ]]; then
     bspc monitor eDP1 -d 1 2 3 4 7 8 5 6 

	 bsp-layout set tall 1
	 bsp-layout set tall 2
	 bsp-layout set tall 3
	 bsp-layout set tall 4
	 bsp-layout set tall 5
	 bsp-layout set tall 6
 elif [[ $(hostname) == 'Battlestation' ]]; then
	 bspc monitor HDMI-0 -d 2 5 7 8
     bspc monitor DP-0 -d 1 4
     bspc monitor DP-2 -d 3 6 9 

	 bsp-layout set even 1
	 bsp-layout set tall 2
	 bsp-layout set tiled 3
	 bsp-layout set even 4
	 bsp-layout set tall 5
	 bsp-layout set tiled 6
 elif [[ $(hostname) == 'c3po' ]]; then
     bspc monitor -d 1 2 3 4 5 6 7 
	 bsp-layout set tall 1
	 bsp-layout set tall 2
	 bsp-layout set tall 3
	 bsp-layout set tall 4
	 bsp-layout set tall 5
	 bsp-layout set tall 6
 fi




###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###

bspc rule -a Opera desktop=5
bspc rule -a URxvt:Music desktop=8
bspc rule -a URxvt:MusicVis desktop=8
bspc rule -a URxvt:TempD1 desktop=1 
bspc rule -a Gnome-disks state=floating


bspc rule -a URxvt:youtubi state=floating sticky=on rectangle=500x100+250+120
bspc rule -a firefox sticky=on state=floating rectangle=930x1020+10+40
bspc rule -a KeePassXC sticky=on state=floating 
#Temp terminals
bspc rule -a St:TempQ1 state=floating rectangle=930x510+10+40
bspc rule -a St:TempQ2 state=floating rectangle=930x510+10+560
bspc rule -a St:TempQ3 state=floating rectangle=930x510+980+40
bspc rule -a St:TempQ4 state=floating rectangle=930x510+980+560
bspc rule -a St:TempH1 state=floating rectangle=930x1020+10+40
bspc rule -a URxvt:TempH1 state=floating rectangle=930x1020+10+40
bspc rule -a St:TempH2 state=floating rectangle=930x1020+980+40
bspc rule -a St:TempScript1 state=floating rectangle=930x510+10+40
bspc rule -a St:TempScript2 state=floating rectangle=930x510+980+40
# bspc rule -a St:TempH1 state=floating rectangle=930x1020+10+40

bspc rule -a URxvt:Music state=pseudo_tiled rectangle=930x520+980+40
bspc rule -a URxvt:MusicVis state=pseudo_tiled rectangle=1280x300+980+40

~/.scripts/bspwm/bsp_floating_workspace &
~/.scripts/bspwm/bsp_pseudotiling_workspace &
~/.scripts/sleepAndExec.sh picom &
unclutter & #Hide mouse when not moved
