#!/bin/sh
# Simple script to toggle a node to fullscreen mode in bspwm

if [ -z "$(bspc query -N -n .focused.fullscreen -d focused)" ]; then
  bspc node focused.tiled -t fullscreen
  ~/.scripts/bspwm/bsphide

else
  bspc node focused.fullscreen -t tiled
  ~/.scripts/bspwm/bspunhide
fi

